<?php
/**
 * @var $block \AdiDev\DevSupport\Block\Data
 */

$apiData = $block->getAPIData();
var_dump($apiData);

?>

<div class="container">
    <h2>Data from API</h2>
    <?php if (!empty($apiData) && isset($apiData['setup']) && isset($apiData['punchline'])): ?>
        <p><strong>Setup:</strong> <?php echo $apiData['setup']; ?></p>
        <p><strong>Punchline:</strong> <?php echo $apiData['punchline']; ?></p>
    <?php else: ?>
        <p>No joke available from the API.</p>
    <?php endif; ?>
</div>

<!-- // Do not add any logic to this file. This file only contains presentation layer. -->

